# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SJ\Desktop\handwritingNumberalsRecognition\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(611, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        icon = QtGui.QIcon.fromTheme(":/img/icon.jpg")
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_writingBoard = QtWidgets.QLabel(self.centralwidget)
        self.label_writingBoard.setGeometry(QtCore.QRect(-10, 39, 621, 581))
        self.label_writingBoard.setMinimumSize(QtCore.QSize(100, 10))
        self.label_writingBoard.setMaximumSize(QtCore.QSize(660, 16777215))
        self.label_writingBoard.setMouseTracking(True)
        self.label_writingBoard.setAutoFillBackground(True)
        self.label_writingBoard.setObjectName("label_writingBoard")
        self.labelResult = QtWidgets.QLabel(self.centralwidget)
        self.labelResult.setGeometry(QtCore.QRect(3, 1, 611, 21))
        self.labelResult.setMinimumSize(QtCore.QSize(100, 10))
        self.labelResult.setMaximumSize(QtCore.QSize(660, 16777215))
        self.labelResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResult.setObjectName("labelResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionrecognize = QtWidgets.QAction(MainWindow)
        self.actionrecognize.setObjectName("actionrecognize")
        self.actionundo = QtWidgets.QAction(MainWindow)
        self.actionundo.setObjectName("actionundo")
        self.actionrewrite = QtWidgets.QAction(MainWindow)
        self.actionrewrite.setObjectName("actionrewrite")
        self.actionimport = QtWidgets.QAction(MainWindow)
        self.actionimport.setObjectName("actionimport")
        self.menu.addAction(self.actionrecognize)
        self.menu.addAction(self.actionundo)
        self.menu.addSeparator()
        self.menu.addAction(self.actionrewrite)
        self.menu.addAction(self.actionimport)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_writingBoard.setText(_translate("MainWindow", "                               写字板"))
        self.labelResult.setText(_translate("MainWindow", "识别结果"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionrecognize.setText(_translate("MainWindow", "识别"))
        self.actionrecognize.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionundo.setText(_translate("MainWindow", "撤销"))
        self.actionundo.setIconText(_translate("MainWindow", "撤销"))
        self.actionundo.setToolTip(_translate("MainWindow", "撤销"))
        self.actionundo.setShortcut(_translate("MainWindow", "Ctrl+Z, Ctrl+U"))
        self.actionrewrite.setText(_translate("MainWindow", "重写"))
        self.actionrewrite.setShortcut(_translate("MainWindow", "Ctrl+Shift+R"))
        self.actionimport.setText(_translate("MainWindow", "导入图片"))
        self.actionimport.setShortcut(_translate("MainWindow", "Ctrl+I, Ctrl+O"))
import resource_rc
